-- prevent wireshark loading this file as plugin
if not _G['maritimedissector'] then return end

-- List of known Talker IDs (Source: NMEA Revealed by Eric S. Raymond, htps://gpsd.gitlab.io/gpsd/NMEA.html, 4th Dec. 2019)
local known_talkers = {
    AB="Independent AIS Base Station",
    AD="Dependent AIS Base Station",
    AG="Autopilot - General",
    AP="Autopilot - Magnetic",
    BD="BeiDou (China)",
    BN="Bridge navigational watch alarm system",
    CC="Computer - Programmed Calculator",
    CD="Communications - Digital Selective Calling (DSC)",
    CM="Computer - Memory Data",
    CS="Communications - Satellite",
    CT="Communications - Radio-Telephone (MF/HF)",
    CV="Communications - Radio-Telephone (VHF)",
    CX="Communications - Scanning Receiver",
    DE="DECCA Navigation",
    DF="Direction Finder",
    DM="Velocity Sensor, Speed Log, Water, Magnetic",
    DU="Duplex repeater station",
    EC="Electronic Chart Display & Information System (ECDIS)",
    EP="Emergency Position Indicating Beacon (EPIRB)",
    ER="Engine Room Monitoring Systems",
    GA="Galileo Positioning System",
    GB="BeiDou (China)",
    GL="GLONASS, according to IEIC 61162-1",
    GN="Mixed GPS and GLONASS data, according to IEIC 61162-1",
    GP="Global Positioning System (GPS)",
    HC="Heading - Magnetic Compass",
    HE="Heading - North Seeking Gyro",
    HN="Heading - Non North Seeking Gyro",
    II="Integrated Instrumentation",
    IN="Integrated Navigation",
    LA="Loran A",
    LC="Loran C",
    MP="Microwave Positioning System",
    NL="Navigation light controller",
    OM="OMEGA Navigation System",
    OS="Distress Alarm System",
    QC="QZSS regional GPS augmentation system (Japan)",
    RA="RADAR and/or ARPA",
    SD="Sounder, Depth",
    SN="Electronic Positioning System, other/general",
    SS="Sounder, Scanning",
    TI="Turn Rate Indicator",
    TR="TRANSIT Navigation System",
    UP="Microprocessor controller",
    VD="Velocitiy Sensor, Doppler, other/general",
    VW="Velocity Sensor, Speed Log, Water, Mechanical",
    WI="Weather Instruments",
    YC="Transducer - Temperature",
    YD="Transducer - Displacement, Angular or Linear",
    YF="Transducer - Frequency",
    YL="Transducer - Level",
    YP="Transducer - Pressure",
    YR="Transducer - Flow Rate",
    YT="Transducer - Tachometer",
    YV="Transducer - Volume",
    YX="Transducer",
    ZA="Timekeeper - Atomic Clock",
    ZC="Timekeeper - Chronometer",
    ZQ="Timekeeper - Quartz",
    ZV="Timekeeper - Radio Update, WWV or WWVH"
}

return known_talkers